### ISSUE TITLE
Todoist not available in Online Accounts

### ISSUE THREAD

**Issue by aadilayub** [dukex/gnome-shell-extension-most-important-task#2]
Per [this commit](https://gitlab.gnome.org/GNOME/gnome-online-accounts/commit/bf77325d847d2878159e8ba2677768b2fe6386a6), Todoist has been removed from GNOME Online Accounts. 

Is it possible to use this extension by manually connecting it to our Todoist API key instead?

**Comment by dukex** [comment]
Hi @aadilayub, the problem was fixed, thanks for the report and sorry the delay
